refactor(pre-commit): simplify

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# Do not source bashrc with set -e or set -u, as it may contain commands that fail or reference unset variables, which would cause the pre-commit hook to fail unexpectedly.
+# Do not source bashrc with set -e, as it may contain commands that fail, which would cause the pre-commit hook to fail unexpectedly.
 
 if [ -f "$HOME/.bashrc" ]; then
   source "$HOME/.bashrc"
@@ -9,17 +9,9 @@ fi
 # Safety on
 set -e
 
-## "import" env vars before we `set -u`
-#
-# Do not set -u before exporting environment variables, as this will cause premature failures
-
-env_pre_commit_override="$PRE_COMMIT_OVERRIDE"
-
-# Strict mode on
-set -u
 
 # Skip if PRE_COMMIT_OVERRIDE is set
-if [ "$env_pre_commit_override" = '1' ]; then
+if [ "$PRE_COMMIT_OVERRIDE" = "1" ]; then
   echo '[pre-commit] Skipped (PRE_COMMIT_OVERRIDE=1)'
   exit 0
 fi
